### ISSUE TITLE
Add new target SPEEDYBEE F405AIO

### ISSUE THREAD

**Issue by reubenfinch** [qqqlab/madflight#30]
Please add a target for the [SPEEDYBEE F405AIO](https://www.speedybee.com/speedybee-f405-aio-40a-bluejay-25-5x25-5-3-6s-flight-controller/)

I'm not sure how different it is to the SPEEDYBEE F405.

betaflight has a target [file](https://github.com/betaflight/config/blob/master/configs/SPEEDYBEEF405AIO/config.h) , but it seems the python converter script is no longer operational.

**Comment by qqqlab** [comment]
You have to run the python converter yourself, it is not an automated process. 

See https://github.com/qqqlab/madflight/blob/main/extras/betaflight_target_converter/readme.md
