### ISSUE TITLE
need help regarding bmi270

### ISSUE THREAD

**Issue by skshadan** [qqqlab/madflight#32]
Hi! I need some help with the BMI270 as I'm experiencing some issues. Is there a way I can contact you?

Thanks!

**Comment by qqqlab** [comment]
Hi @skshadan, you found the way to contact me :-) Just post your issue here.

**Comment by skshadan** [comment]
hey man, thanks for replying...

check this out :/
https://github.com/espressif/esp-drone/discussions/98

**Comment by qqqlab** [comment]
`#define IMU_USE  IMU_USE_SPI_BMI270`

**Comment by skshadan** [comment]
I want to use this in esp-drone, how can i do this?

**Comment by qqqlab** [comment]
Well, ask the esp-drone people...
